# This file is used to configure the Travis CI tests for this repository

matrix:
  include:

    - name: 'File Formatting Checks'
      language: minimal
      script:
        # Check for UTF-8 BOM file encoding
        - find "${TRAVIS_BUILD_DIR}" -path "${TRAVIS_BUILD_DIR}/.git" -prune -or -type f -exec grep --files-with-matches --binary-files=without-match $'\xEF\xBB\xBF' '{}' \; -exec echo 'UTF-8 BOM encoding detected.' \; -exec false '{}' +
        # Check for files starting with a blank line
        - find "${TRAVIS_BUILD_DIR}" -path "${TRAVIS_BUILD_DIR}/.git" -prune -or -type f -print0 | xargs -0 -L1 bash -c 'head -1 "$0" | grep --binary-files=without-match --regexp="^$"; if [[ "$?" == "0" ]]; then echo "Blank line found at start of $0."; false; fi'
        # Check for tabs
        - find "${TRAVIS_BUILD_DIR}" -path "${TRAVIS_BUILD_DIR}/.git" -prune -or \( -not -path "${TRAVIS_BUILD_DIR}/ino-hardware-package-list.tsv" -and -type f \) -exec grep --with-filename --line-number --binary-files=without-match --regexp=$'\t' '{}' \; -exec echo 'Tab found.' \; -exec false '{}' +
        # Check for trailing whitespace
        - find "${TRAVIS_BUILD_DIR}" -path "${TRAVIS_BUILD_DIR}/.git" -prune -or \( -not -path "${TRAVIS_BUILD_DIR}/ino-hardware-package-list.tsv" -and -type f \) -exec grep --with-filename --line-number --binary-files=without-match --regexp='[[:blank:]]$' '{}' \; -exec echo 'Trailing whitespace found.' \; -exec false '{}' +
        # Check for non-Unix line endings
        - find "${TRAVIS_BUILD_DIR}" -path "${TRAVIS_BUILD_DIR}/.git" -prune -or -type f -exec grep --files-with-matches --binary-files=without-match --regexp=$'\r$' '{}' \; -exec echo 'Non-Unix EOL detected.' \; -exec false '{}' +
        # Check for blank lines at end of files
        - find "${TRAVIS_BUILD_DIR}" -path "${TRAVIS_BUILD_DIR}/.git" -prune -or -type f -print0 | xargs -0 -L1 bash -c 'tail -1 "$0" | grep --binary-files=without-match --regexp="^$"; if [[ "$?" == "0" ]]; then echo "Blank line found at end of $0."; false; fi'
        # Check for files that don't end in a newline (https://stackoverflow.com/a/25686825)
        - find "${TRAVIS_BUILD_DIR}" -path "${TRAVIS_BUILD_DIR}/.git" -prune -or -type f -print0 | xargs -0 -L1 bash -c 'if test "$(grep --files-with-matches --binary-files=without-match --max-count=1 --regexp='.*' "$0")" && test "$(tail --bytes=1 "$0")"; then echo "No new line at end of $0."; false; fi'


    - name: 'Spell Check'
      language: python
      python: 3.6
      install:
        # Install codespell
        # https://github.com/codespell-project/codespell
        - pip install codespell

      script:
        - codespell --skip="${TRAVIS_BUILD_DIR}/.git" "$TRAVIS_BUILD_DIR"


notifications:
  email:
    on_success: always
    on_failure: always
  webhooks:
    urls:
      # Use TravisBuddy to automatically comment on any pull request that results in a failing CI build
      - https://www.travisbuddy.com/
    on_success: never
    on_failure: always
